// apps/astro/src/components/common/LinkItem.tsx
import { FaGithub, FaGlobe } from 'react-icons/fa';
import { Wrap } from 'styled-system/jsx';
import { ComponentUtilsLink, Enum_Componentutilslink_Type } from '~/graphql/generated/client';
import { Link } from '../ui/link';
import { Text } from '../ui/text';

const processUrl = (link: Pick<ComponentUtilsLink, 'url' | 'type'>) => {
  switch (link.type) {
    case Enum_Componentutilslink_Type.Github:
      return link.url?.split('github.com/').splice(-1)[0];
    default:
      return link.url;
  }
};

const linkIcon = (link: Pick<ComponentUtilsLink, 'type'>) => {
  switch (link.type) {
    case Enum_Componentutilslink_Type.Github:
      return FaGithub;
    case Enum_Componentutilslink_Type.Web:
      return FaGlobe;
    default:
      return null;
  }
};

export const LinkItem = ({
  data,
  Icon: _icon,
  linkText
}: {
  data: Omit<ComponentUtilsLink, 'id'>;
  Icon?: React.FunctionComponent;
  linkText?: string;
}) => {
  const Icon = _icon ? _icon : linkIcon(data);
  const text = linkText ? linkText : processUrl(data);
  return (
    <Wrap gap="2">
      {Icon && <Icon />}
      {data.title}
      <Text>:</Text>
      <Link href={data.url ?? ''} target="_blank">
        {text}
      </Link>
    </Wrap>
  );
};

// client/src/components/core/LinkItem.svelte
<script lang="ts">
	import type { ComponentUtilsLink } from '@graphql/generated/client';
	import Typography from './Typography.svelte';

	import Fa from 'svelte-fa';
	import { faGlobe } from '@fortawesome/free-solid-svg-icons';
	import { faGithub } from '@fortawesome/free-brands-svg-icons';
	export let link: ComponentUtilsLink;

	const processUrl = (link: ComponentUtilsLink) => {
		switch (link.type) {
			case 'github':
				return link.url?.split('github.com/').splice(-1)[0];
			default:
				return link.url;
		}
	};

	const linkIcon = (link: ComponentUtilsLink) => {
		switch (link.type) {
			case 'github':
				return faGithub;
			case 'web':
				return faGlobe;
			default:
				return null;
		}
	};
</script>

<Typography>
	{#if linkIcon(link)}
		<Fa size="lg" icon={linkIcon(link)} class="inline mr-1" />
	{:else}{link?.title}{/if}:
	<a target="_blank" rel="noreferrer" class="text-blue-400 underline" href={link?.url}
		>{processUrl(link)}</a
	>
</Typography>
