// apps/astro/src/components/projects/ProjectCard.tsx
import { FaGithub, FaGlobe, FaPhotoVideo } from 'react-icons/fa';
import { Box, Center, Stack, styled, Wrap } from 'styled-system/jsx';
import { formatMonthYear, parseDate } from 'utils/date';
import { getMediaUrl } from 'utils/media';
import { Enum_Componentutilslink_Type, ProjectPreviewFragment } from '~/graphql/generated/client';
import { Languages } from '~/i18n/ui';
import { IconButton } from '../ui/icon-button';
import { Link } from '../ui/link';
import { Text } from '../ui/text';

export const ProjectCard = (props: { data: ProjectPreviewFragment; locale: Languages }) => {
  const { data, locale } = props;
  const { title, description, slug, banner, media, date, category, links } = data;
  const image = banner?.data?.attributes ?? media?.data?.[0]?.attributes;
  const link = links?.find((l) => l?.type === Enum_Componentutilslink_Type.Web);
  const ghLink = links?.find((l) => l?.type === Enum_Componentutilslink_Type.Github);

  return (
    <Stack h="full">
      <Link href={`/${locale}/projects/${slug}`} data-astro-prefetch="hover" flex={1}>
        <Stack gap="0.5" h="full">
          <Box borderRadius="l2" backgroundColor="bg.muted" overflow="hidden">
            {image ? (
              <styled.img
                src={getMediaUrl(image.url, {}, import.meta.env.PUBLIC_API_URL) ?? ''}
                alt={image.name}
                style={{
                  viewTransitionName: `project-image-${slug}`
                }}
                aspectRatio="4 / 3"
                objectPosition="center"
                objectFit="contain"
                width="full"
              />
            ) : (
              <Center aspectRatio="4 / 3" color="fg.subtle" fontSize="xl">
                <FaPhotoVideo />
              </Center>
            )}
          </Box>
          <Text
            style={{
              viewTransitionName: `project-title-${slug}`
            }}
            fontWeight="bold"
          >
            {title}
          </Text>
          <Wrap gap="1" rowGap="0.5" color="fg.subtle" fontSize="sm">
            <Text>{category?.name}</Text> <Text>|</Text>
            <Text>{formatMonthYear(parseDate(date), locale)}</Text>
          </Wrap>
          <Text fontSize="sm">{description}</Text>
        </Stack>
      </Link>
      <Wrap w="full">
        {link?.url && (
          <Link href={link?.url} target="_blank">
            <IconButton size="xs" variant="subtle">
              <FaGlobe />
            </IconButton>
          </Link>
        )}
        {ghLink?.url && (
          <Link href={ghLink.url} target="_blank">
            <IconButton size="xs" variant="subtle">
              <FaGithub />
            </IconButton>
          </Link>
        )}
      </Wrap>
    </Stack>
  );
};

// client/src/components/projects/ProjectCard.svelte
<script lang="ts">
	import type { ProjectPreviewFragment } from '@graphql/generated/client';
	import { getMediaUrl } from '@utils/media';
	import Typography from '@components/core/Typography.svelte';
	import { formatMonthYear, parseDate } from '@utils/date';
	import { locale, t } from '@i18n';
	import TagItem from '@components/tags/TagItem.svelte';
	import { sortTags } from '@utils/tags';

	export let project: Pick<
		ProjectPreviewFragment,
		'title' | 'media' | 'description' | 'slug' | 'date' | 'tags' | 'category'
	>;

	let _class = '';
	$: subtitle = [
		project?.date ? formatMonthYear(parseDate(project?.date), $locale) : null,
		project?.category?.data?.attributes?.name
	]
		.filter((f) => !!f)
		.join(' | ');
	export { _class as class };
</script>

<a href="/projects/{project.slug}" class="block md:min-h-[250px] {_class || ''}">
	<div
		class=" bg-white shadow-md rounded-md flex flex-col h-full transtion-shadow transition-transform hover:shadow-lg hover:scale-105"
	>
		{#if project.media?.data[0]?.attributes?.url}
			<div
				class="rounded-t-md bg-cover bg-center bg-no-repeat h-64"
				style:background-image="url('{getMediaUrl(project.media?.data[0]?.attributes?.url, {
					height: 400
				})}')"
			/>
		{/if}
		<div class="w-full h-full flex-1 p-2 ">
			<Typography variant="h5" class="mb-1 text-bold">{project.title}</Typography>
			{#if subtitle}<Typography variant="subtitle" class="mb-1">{subtitle}</Typography>{/if}
			{#if project.tags?.data && project.tags?.data?.length > 0}
				<div class="flex items-center flex-wrap">
					<Typography variant="subtitle" class="mr-2">{$t('common.tags')}:</Typography>
					{#each sortTags(project?.tags?.data) as tag}
						{#if tag.attributes}
							<TagItem tag={tag?.attributes} class="mr-1 my-1" />
						{/if}
					{/each}
				</div>
			{/if}
			{#if project.description}
				<p>{project.description}</p>
			{/if}
		</div>
	</div>
</a>
